name: Deploy on pypi.org

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v5

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.x
          cache: "poetry"
          cache-dependency-path: poetry.lock

      - name: Install dependencies
        run: poetry install

      - name: Build packages
        run: poetry build
  
      - name: Publish on pypi.org
        uses: pypa/gh-action-pypi-publish@v1.13.0
